---
Name: fancydevbuildconfig
After: 'framework/*','cms/*'
---
LeftAndMain:
  extra_requirements_javascript:
    - 'fancy-devbuild/javascript/LeftAndMain.Fancy-devbuild.js'
  extra_requirements_css:
    - 'fancy-devbuild/css/fancydevbuild.css'
ContentController:
  extensions:
    - FancyDevBuild
